project_id = "mnukhzjcvbwpvktxqlej"

[functions.mailchimp-subscribe]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.check-mailchimp-member]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.create-existing-profiles]
verify_jwt = true

[functions.send-announcement-email]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.send-chat-notification]
verify_jwt = true

[functions.admin-create-enrollment]
verify_jwt = true

[functions.get-stripe-session-details]
verify_jwt = true

[functions.admin-change-password]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-broadcast-message]
verify_jwt = true

[functions.send-five-language-confirmation]
verify_jwt = true
