project_id = "mnukhzjcvbwpvktxqlej"

[functions.mailchimp-subscribe]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.check-mailchimp-member]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.create-existing-profiles]
verify_jwt = true

[functions.setup-admin]
verify_jwt = false