project_id = "mnukhzjcvbwpvktxqlej"

[functions.mailchimp-subscribe]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.check-mailchimp-member]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.create-existing-profiles]
verify_jwt = true

[functions.send-announcement-email]
verify_jwt = true

[functions.generate-vapid-keys]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.get-stripe-session-details]
verify_jwt = true